config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord

  belongs_to :user

  #if user submits a friend with same insta as alreadyexisting friend then dont accept and give error
  validates :insta, uniqueness: true
  validates :email, uniqueness: true
  validates :contact, uniqueness: true

  #validate name is min 3 max 25 
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  #validate email is correct 
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  #validate contact is 10 exact
  validates :contact, presence: true, length: { is: 10 }
  #validate insta is present
  validates :insta, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :friends
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #validate that while sign in email must be of format email
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 

  #validate that while sign in password all necessary pasword instructions like atleast 1 uppercase , atleast 1 special char atleast 1 number atleas length 8 chars max length 50 chars
  validates :password, format: { with: /\A(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[[:^alnum:]])/x, message: "must contain atleast 1 uppercase, atleast 1 special char, atleast 1 number" }
  validates :password, length: { in: 8..50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  #if user is not authenticated he cannot edit update or destroy a friend if he tries to do so he will be redirected to login page
  before_action :authenticate_user!, only: %i[ edit update destroy ]
  #if user is not the owner of the friend he cannot edit update or destroy a friend
  before_action :check_user, only: %i[ edit update destroy ]
  
  def check_user
    if current_user.id != @friend.user_id
      redirect_to friends_path, notice: "You are not authorized to perform this action"
    end
  end

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:name, :email, :contact, :insta, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @text="Hello world"
    @sum= 2+2       #we use @ cause we need instance variables and we will be using these in view so it can;t be local varialbles
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, class: "contents") do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li>- <%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :contact %>
    <%= form.text_field :contact, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :insta %>
    <%= form.text_field :insta, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.hidden_field :user_id, id: :friend_user_id, value:current_user.id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
  </form>

<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= friend.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= friend.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Contact:</strong>
    <%= friend.contact %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Insta:</strong>
    <%= friend.insta %>
  </p>

</div>

app/views/friends/edit.html.erb
<div class="mx-auto md:w-2/3 w-1/3">
  <h1 class="font-bold text-4xl">Editing friend</h1>

  <%= render "form", friend: @friend %>

  <%= link_to "Show this friend", @friend, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to friends", friends_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/friends/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Friends" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl py-6">Your Friends list</h1>
  </div>

  <div id="friends" class="min-w-full">
      <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Name
                </th>
                <th scope="col" class="px-6 py-3">
                    Email
                </th>
                <th scope="col" class="px-6 py-3">
                    Contact
                </th>
                <th scope="col" class="px-6 py-3">
                    Insta id
                </th>
                <th scope="col" class="px-6 py-3">
                </th>
            </tr>
        </thead>
        <tbody>
            <%# show only those friends whose owner is current user not all the friends %>
              <% @friends.each do |friend| %>
              <% if friend.user_id == current_user.id %>
            <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    <%= friend.name %>
                </th>
                <td class="px-6 py-4">
                    <%= friend.email %>
                </td>
                <td class="px-6 py-4">
                    <%= friend.contact %>
                </td>
                <td class="px-6 py-4">
                    <%= friend.insta %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                    <%# if user is owner of this friend then only he should be able to see the three buttons also see show button  %>
                    <% if current_user == friend.user %>
                    <a href="/friends/<%= friend.id %>/edit" class="text-blue-600
                    hover:text-blue-900 px-2">Edit</a>
                    <a href="/friends/<%= friend.id %>" data-confirm="Are you sure?" data-method="delete" rel="nofollow" class="text-red-600 hover:text-red-900 px-2">Destroy</a>
                    <%# show button as well %>
                    <a href="/friends/<%= friend.id %>" class="text-blue-600 hover:text-blue-900 px-2">Show</a>
                    <% end %>   
                </td>
            </tr>
            <% end %>
            <% end %>
        </tbody>
    </table>
</div>
  </div>
  <div class="flex justify-between items-center py-4">
    <%= link_to "New friend", new_friend_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
</div>

app/views/friends/new.html.erb
<div class="mx-auto md:w-2/3 w-1/3">
  <h1 class="font-bold text-4xl">New friend</h1>

  <%= render "form", friend: @friend %>

  <%= link_to "Back to friends", friends_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/friends/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @friend %>
  
    <%= link_to "Edit this friend", edit_friend_path(@friend), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to friends", friends_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this friend", @friend, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="max-w-md mx-auto">
  <h1 class="font-bold text-4xl">Home#index</h1>
  <p>Find me in app/views/home/index.html.erb</p>
  <p> <%= @text %> </p>
  <p> <%= @sum %> </p>
</div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.css" rel="stylesheet" />
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%# render header from shared/header using render commmand %>
      <%= render 'shared/header' %>
      <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
        <%= yield %>
      </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.js"></script>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="bg-white dark:bg-gray-900 shadow:xl fixed w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
  <a href="/" class="flex items-center ">
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-black-900">Friends</span>
  </a>
  <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
      <% if !user_signed_in? %>
        <div class="pr-4">    
        <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><%= link_to "Sign In", new_user_session_path %></button>
        </div>
        <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><%= link_to "Sign Up", new_user_registration_path %></button>
      <% else %>
        <div class="pr-4">
        <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %></button>
        </div>
        <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><%= link_to "Edit Profile", edit_user_registration_path %></button>
      <% end %>
      <button data-collapse-toggle="navbar-sticky" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-sticky" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
    </button>
  </div>
  <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
    <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
      <li>
        <a href="/friends" class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" aria-current="page">Your Friends</a>
      </li>
      <li>
        <a href="/friends/new" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Add Friend</a>
      </li>
    </ul>
  </div>
  </div>
</nav>